### ISSUE TITLE
Squash html charcter encoding error

### ISSUE THREAD

**Issue by lucywyman** [scribd/robot-fruit-hunt#15]
Hello!  I was hacking on fruit robot (which is such a fun challenge, by the way!), and noticed a few errors in the console.  One of them is outdated jquery, which seems like it might be a bit of an unnecessary pain to fix (though could certainly be done -- I can work on it if you'd like), and the other was unspecified charset, which is super easy to fix.  Submitting PR, but thought I'd file an issue first for good practice.

**Comment by egonSchiele** [comment]
Thanks! Merged.
