### ISSUE TITLE
Decimal get_my_item_count() and get_opponent_item_count()

### ISSUE THREAD

**Issue by michaelvillar** [scribd/robot-fruit-hunt#3]
I think there is a bug with get_my_item_count() and get_opponent_item_count(). 
These two functions don't return decimal. 
When players have 0.5, they return 0. 
This works locally though so this is not related to this repo but I didn't know where to contact you.

Example of failed match : http://www.scribd.com/job_game/match/295703 
This line for example 1 / 1 / 0 / 0 / 1 
- first number is the fruit type 
- second number is the total fruits 
- third number is my fruits 
- fourth number is opponent fruit 
- fifth number is irrelevant 

(You'll never see 0.5 in the third or fourth number..)

**Comment by matthiaskramm** [comment]
Hi Michael,

Huh. I can't believe that bug stayed undetected for so long.
Thanks for reporting it!

It should be fixed now- let me know in case things aren't working
correctly for you now.

I guess with this fix a few of our bots will now behave quite 
differently. :)

Matthias

-----Original Message-----
From: Michael Villar
Sent: Fri, May 25, 2012 at 08:40:17AM -0700
To matthiaskram
I think there is a bug with get_my_item_count() and get_opponent_item_count(). 
These two functions don't return decimal. 
When players have 0.5, they return 0. 
This works locally though so this is not related to this repo but I didn't know where to contact you.

Example of failed match : http://www.scribd.com/job_game/match/295703 
This line for example 1 / 1 / 0 / 0 / 1 
- first number is the fruit type 
- second number is the total fruits 
- third number is my fruits 
- fourth number is opponent fruit 
- fifth number is irrelevant 
  (You'll never see 0.5 in the third or fourth number..)

---

Reply to this email directly or view it on GitHub:
https://github.com/scribd/robot-fruit-hunt/issues/3

**Comment by michaelvillar** [comment]
You're welcome :)
